<?php
declare(strict_types=1);
$pageTitle = 'Reports';
$rootDir   = dirname(dirname(dirname(__FILE__)));
require_once $rootDir . '/includes/header.php';
requireRole(['admin','manager']);

// Past reports
$pastReports = $pdo->query(
    "SELECT r.*, u.full_name AS generated_by_name
     FROM reports r
     LEFT JOIN users u ON u.user_id = r.generated_by
     ORDER BY r.generated_at DESC
     LIMIT 20"
)->fetchAll();
?>

<div class="page-header">
  <div>
    <h1>Reports</h1>
    <p class="breadcrumb">Generate PDF reports and send by email</p>
  </div>
</div>

<!-- Report type selector -->
<h2 class="section-title">Select Report Type</h2>
<div class="report-cards" id="reportCards">
  <div class="report-card" data-type="inventory" onclick="selectReport(this)">
    <span class="report-icon">&#9636;</span>
    <div class="report-name">Inventory Report</div>
    <div class="report-desc">Current stock levels, low-stock items, and reorder status</div>
  </div>
  <div class="report-card" data-type="maintenance_history" onclick="selectReport(this)">
    <span class="report-icon">&#9881;</span>
    <div class="report-name">Maintenance History</div>
    <div class="report-desc">All completed maintenance tasks with costs and outcomes</div>
  </div>
  <div class="report-card" data-type="asset_condition" onclick="selectReport(this)">
    <span class="report-icon">&#9874;</span>
    <div class="report-name">Asset Condition</div>
    <div class="report-desc">Full asset register with current condition status</div>
  </div>
  <div class="report-card" data-type="scheduled_maintenance" onclick="selectReport(this)">
    <span class="report-icon">&#9783;</span>
    <div class="report-name">Scheduled Maintenance</div>
    <div class="report-desc">Upcoming and overdue maintenance schedules</div>
  </div>
</div>

<!-- Generate form -->
<div class="card" style="margin-bottom:2rem;">
  <div class="card-header">
    <span class="card-title">Generate Report</span>
  </div>
  <form method="POST" action="<?= BASE_URL ?>modules/reports/generate.php" novalidate>
    <?= csrfField() ?>
    <input type="hidden" name="report_type" id="report_type" value="">
    <div class="form-grid">
      <div class="form-group">
        <label class="form-label">Date From (optional)</label>
        <input type="date" name="date_from" class="form-control">
      </div>
      <div class="form-group">
        <label class="form-label">Date To (optional)</label>
        <input type="date" name="date_to" class="form-control" value="<?= date('Y-m-d') ?>">
      </div>
      <div class="form-group full">
        <label class="form-label">Email Recipients (comma-separated)</label>
        <input type="text" name="recipient_emails" class="form-control"
               placeholder="admin@amims.ng, manager@amims.ng">
        <span class="form-hint">Leave blank to skip email sending.</span>
      </div>
    </div>
    <div class="form-actions">
      <button type="submit" class="btn btn-primary" id="genBtn" onclick="return validateReportForm()">
        &#9878; Generate &amp; Download PDF
      </button>
    </div>
  </form>
</div>

<!-- Past reports -->
<?php if (!empty($pastReports)): ?>
<div class="card">
  <div class="card-header">
    <span class="card-title">Recent Reports</span>
  </div>
  <div class="table-wrap">
    <table>
      <thead>
        <tr><th>#</th><th>Type</th><th>Generated By</th><th>Generated At</th><th>Recipients</th><th>Download</th></tr>
      </thead>
      <tbody>
        <?php foreach ($pastReports as $i => $r): ?>
        <tr>
          <td><?= $i+1 ?></td>
          <td><?= sanitize(str_replace('_',' ',ucwords($r['report_type']))) ?></td>
          <td><?= sanitize($r['generated_by_name'] ?? '—') ?></td>
          <td><?= formatDateTime($r['generated_at']) ?></td>
          <td><?= sanitize($r['sent_to_emails'] ?? '—') ?></td>
          <td>
            <?php if ($r['file_path'] && file_exists($rootDir . '/../../' . $r['file_path'])): ?>
              <a href="<?= BASE_URL . sanitize($r['file_path']) ?>" class="btn btn-secondary btn-sm" download>Download</a>
            <?php else: ?>
              <span class="text-muted">—</span>
            <?php endif; ?>
          </td>
        </tr>
        <?php endforeach; ?>
      </tbody>
    </table>
  </div>
</div>
<?php endif; ?>

<script>
window.BASE_URL   = '<?= BASE_URL ?>';
window.CSRF_TOKEN = '<?= generateCsrfToken() ?>';

function selectReport(card) {
  document.querySelectorAll('.report-card').forEach(function(c) { c.classList.remove('selected'); });
  card.classList.add('selected');
  document.getElementById('report_type').value = card.getAttribute('data-type');
}

function validateReportForm() {
  var type = document.getElementById('report_type').value;
  if (!type) { alert('Please select a report type first.'); return false; }
  return true;
}
</script>
<script src="<?= BASE_URL ?>assets/js/app.js"></script>
</main><footer class="footer">&copy; <?= date('Y') ?> AMIMS</footer>
</div></div></body></html>
